import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link href="https://css.gg/css" rel="stylesheet" />
          <link href="https://unpkg.com/css.gg/icons/icons.css" rel="stylesheet" />
          <link
            href="https://cdn.jsdelivr.net/npm/css.gg/icons/icons.css"
            rel="stylesheet"
          />
      </head>
      
      <body>{children}
      
      </body>
      
    </html>
  )
}
